# Describes the format for available e-Connect services

arm_sectors:
  name: Arm Sectors
  description: Arm one or multiple sectors.
  target:
    entity:
      integration: econnect_metronet
      domain: binary_sensor
      device_class: "sector"
  fields:
    code:
      name: Code
      required: true
      description: A code to trigger the alarm control panel with.
      example: "1234"
      selector:
        text:

disarm_sectors:
  name: Disarm Sectors
  description: Disarm one or multiple sectors.
  target:
    entity:
      integration: econnect_metronet
      domain: binary_sensor
      device_class: "sector"
  fields:
    code:
      name: Code
      required: true
      description: A code to trigger the alarm control panel with.
      example: "1234"
      selector:
        text:
