name: 'Publish'

on:
  release:
    types:
      - published

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  release_zip_file:
    name: Publish integration zip file asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Detect package version
        run: echo "PKG_VERSION=$(hatch version)" >> "$GITHUB_ENV"

      - name: Build release package (tar)
        run: hatch -v build -t sdist

      - name: Build release package (zip)
        run: hatch -v build -t zipped-directory

      - name: Build release package (HACS)
        run: |
          cd ${{ github.workspace }}/custom_components/econnect_metronet
          zip hacs_econnect_metronet.zip -r ./

      - name: Upload release packages
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ${{ github.workspace }}/dist/econnect_metronet-$PKG_VERSION.tar.gz
            ${{ github.workspace }}/dist/econnect_metronet-$PKG_VERSION.zip
            ${{ github.workspace }}/custom_components/econnect_metronet/hacs_econnect_metronet.zip
